name: 'UpdateService'
description: 'Update a service backed by Knative Serving'
inputs:
  service:
    description: Service name
    required: true
  image:
    description: Image
    required: true
  namespace:
    description: Namespace
    required: false
    default: "default"

runs:
  using: "composite"
  steps:
    - uses: Fyve-Labs/actions/configure-aws-credentials@main

    - uses: Fyve-Labs/actions/tailscale@main

    - uses: Fyve-Labs/actions/install-fyve-client@main

    - name: Install Knative Client
      shell: bash
      run: |
        curl -o kn -sfL https://github.com/knative/client/releases/download/knative-v1.18.0/kn-linux-amd64
        sudo install -c -m 0755 kn /usr/local/bin

    - name: Update image
      shell: bash
      run: |
        fyve kubeconfig > kubeconfig
        kn service update $SERVICE --image $IMAGE --kubeconfig=kubeconfig -n $NAMESPACE
      env:
        SERVICE: ${{ inputs.service }}
        NAMESPACE: ${{ inputs.namespace }}
        IMAGE: ${{ inputs.image }}

