name: 'UpdateService'
description: 'Update a service backed by Knative Serving'
inputs:
  service:
    description: Service name
    required: true
  image:
    description: Image
    required: true
  namespace:
    description: Namespace
    required: false
    default: "default"

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::209479271613:role/GithubFederatedIdentityRole
        aws-region: us-east-1

    - uses: Fyve-Labs/actions/tailscale@main
      with:
        authkeySecretName: /headscale/TS_AUTHKEY

    - name: Setup Fyve Cli
      shell: bash
      run: |
        curl -sfL https://github.com/Fyve-Labs/fyve-cli/raw/main/install.sh | bash

    - name: Install Knative Client
      shell: bash
      run: |
        curl -o kn -sfL https://github.com/knative/client/releases/download/knative-v1.18.0/kn-linux-amd64
        sudo install -c -m 0755 kn /usr/local/bin

    - name: Update image
      shell: bash
      run: |
        fyve kubeconfig > kubeconfig
        kn service update $SERVICE --image $IMAGE --kubeconfig=kubeconfig -n $NAMESPACE
      env:
        SERVICE: ${{ inputs.service }}
        NAMESPACE: ${{ inputs.namespace }}
        IMAGE: ${{ inputs.image }}

