inputs:
  role-to-assume:
    description: role-to-assume
    required: false
    default: arn:aws:iam::209479271613:role/GithubFederatedIdentityRole
  aws-region:
    description: AWS region
    required: false
    default: us-east-1

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
