inputs:
  version:
    description: Version
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Setup Fyve Cli
      shell: bash
      run: |
        curl -sfL https://github.com/Fyve-Labs/fyve-cli/raw/main/install.sh | bash

