name: 'Fyve Deploy'
description: 'Deploy Serverless application using Fyve Cli'

inputs:
  work-dir:
    description: Work dir
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: Fyve-Labs/actions/configure-aws-credentials@main

    - uses: Fyve-Labs/actions/tailscale@main

    - uses: Fyve-Labs/actions/install-fyve-client@main

    - name: Fyve Deploy
      shell: bash
      env:
        FYVE_WORK_DIR: ${{ inputs.work-dir }}
      run: |
        if [ "$FYVE_WORK_DIR" != "" ]; then
          if [ ! -d "$FYVE_WORK_DIR" ]; then
            echo Work dir "$FYVE_WORK_DIR" does not exists
            exit 1
          fi
        
          cd $FYVE_WORK_DIR
        fi
        
        fyve deploy

