name: Fyve Deploy

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Fyve-Labs/actions/fyve-deploy@main
        with:
          work-dir: ${{ inputs.path || '' }}
